// Dig.compute
#pragma kernel CSMain

RWStructuredBuffer<float> _Noise;

int _Width;
int _Height;
int _Depth;

float3 _DigPosition;
float _DigRadius;

[numthreads(8, 8, 8)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint DensityWidth = _Width;

    if (id.x >= DensityWidth || id.y >= DensityWidth || id.z >= DensityWidth)
        return;

    uint index = id.x + id.y * DensityWidth + id.z * DensityWidth * DensityWidth;
    float3 voxelPos = float3(id.x, id.y, id.z);

    float dist = distance(voxelPos, _DigPosition);
    if (dist < _DigRadius)
    {
        float fade = smoothstep(_DigRadius, 0.0, dist);
        float current = _Noise[index];
        _Noise[index] = lerp(current, -1.0, fade);
    }
}
